name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/test-docker:latest
    - name: push to DH
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/test-docker:latest
    - name: Run command on remote server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop test-docker
          docker remove test-docker
          cd ${{ secrets.PROJECT_FOLDER }}
          whoami
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/test-docker:latest
          docker run -d --name test-docker -p 5000:5001 test-docker


